
config-version: 2.0.0-Spigot-DEV-119

data:

  # Types: YAML, MongoDB (MongoDB is BETA support)
  type: "yaml"

  # YAML configuration
  # For security reasons, the file name cannot currently be changed.
  yaml:
    file: "data" # Do not change this value.

  # Warning: MongoDB is in BETA support.
  # Warning: It is NOT 100% proven to work correctly, function is BETA.
  # MongoDB configuration (MongoDB is not supported in this version)
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "NameMCAPI"
    collection: "data"


# Server configuration
settings:

  # Debug mode.
  # This is designed more for developers.
  # Default: false
  debug: false

  # Server IP
  # REQUIRED!
  # IP your server.
  # Example: IP: 'hypixel.net' OR IP: 'play.yourdomain.com:25565' OR IP: 'numericip:25565'.
  ip-server: "play.example.com"

  # Online Mode
  # REQUIRED!
  # Q: What is this?
  # A: It is a function to verify the player's uuid through the Mojang API.
  #    For servers that are not premium and do not have a login system that
  #    validates uuid of premium players, if this is your case set the value to “false”.
  # -----------------------------------------------------
  # If your server is no-premium, set the value to "false".
  # If your server is premium, set the value to "true".
  # -----------------------------------------------------
  # Default: true
  online-mode: true

  langs:
    autoDownload: true # Auto download the language file from the GitHub repository. (Recommended enabled)
    lang: "en_US" # Language file. (Default: en_US)

  # RECOMMENDED! Enabled. (In Development)
  cooldown:
    enabled: true
    # Cooldown time in seconds.
    # Default: 300 (5 minutes)
    time: 300

# Integrations configuration
integrations:
  # PlaceholderAPI integration.
  # PlaceholderAPI is a plugin that allows you to use placeholders from other plugins.
  # https://www.spigotmc.org/resources/placeholderapi.6245/
  # -----------------------------------------------------
  # REQUIRED PlaceholderAPI plugin installed.
  # Enable or disable PlaceholderAPI integration. (Recommended enabled | Required PlaceholderAPI plugin)
  # -----------------------------------------------------
  # Default: true
  placeholderapi: true

# Rewards configuration
# Placeholders API no supported (Rewards) in this version, support in next version. (In Development)
rewards:
  # Enable or disable the reward system (Global options).
  # Default: true
  enabled: true

  # Values variables:
  # - %player% = Player name.
  # - %uuid% = Player UUID.
  # - %ip% = Server IP.
  # - %vote_link% = Vote link.
  # - %prefix% = Prefix of the plugin.
  # - %version% = Plugin version.
  # - %author% = Plugin author.

  # Command executed by the console.
  console-cmd:
    enabled: true
    commands:
      - "give %player% diamond 1"
      - "lp user %player% parent add NameMC"
      - "say %player% has voted!"

  # Command executed by the player.
  player-cmd:
    enabled: false
    commands:
      - "/say %player% has voted!"

  # Player send message in chat.
  player-msg:
    enabled: false
    messages:
      - "You have voted!"
      - "You have received a reward!"

