name: NameMCAPI
version: '${project.version}'
main: com.github.happyuky7.nameMCAPIServersMC.NameMCAPIServersMC
api-version: '1.16'
authors: [ Happyuky7 ]
description: NameMC API ServersMC
website: https://github.com/Happyuky7
commands:

  namemc:
    aliases:
      - namemcapi
      - namemcapiserversmc
    usage: /<command>
